_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/Part_3/main.py
        e:
            llcokfluz70u2ta3jxwdy15jsrdjvfsm:
                codePath: Part_3\main.py
                codePathLocal: Part_3\main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999542947840"
                        used: "903009832960"
                email: ivanmartincampoy@gmail.com
                executable: C:\Users\Iván\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 619637efe37aba27ec66c992b9010f319d72b008
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-0874ff1a-4d55-a603-929f-30b09fe083f9
                host: Pc-Ivan
                memory:
                    total: "34290769920"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong\Part_3\main.py
                python: CPython 3.10.10
                root: c:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong
                startedAt: "2025-12-01T10:32:33.176054Z"
                writerId: llcokfluz70u2ta3jxwdy15jsrdjvfsm
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
            "3":
                - 13
                - 16
                - 35
            "4": 3.10.10
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
env_name:
    value: ALE/Skiing-v5
export_path:
    value: ./exports/
policy_type:
    value: CnnPolicy
total_timesteps:
    value: 1000000
