_wandb:
    value:
        cli_version: 0.22.3
        e:
            3uzgqmpcueydw3nujqbhtrsf732i6ej4:
                codePath: Part 1\main.py
                codePathLocal: main.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1022387097600"
                        used: "515822604288"
                email: 1670797uab@gmail.com
                executable: C:\Users\ainav\anaconda3\envs\project_paradigms\python.exe
                git:
                    commit: f59528bdf1497f57e53e99ac139ed6e37f934d9d
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                host: LAPTOP-3ELO2U09
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong\Part 1\main.py
                python: CPython 3.10.19
                root: C:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong\Part 1
                startedAt: "2025-11-20T22:02:53.832087Z"
                writerId: 3uzgqmpcueydw3nujqbhtrsf732i6ej4
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 32
device:
    value: cpu
dnn_sync_freq:
    value: 1000
dnn_update_freq:
    value: 4
epsilon_decay:
    value: 0.995
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.00025
min_epsilon:
    value: 0.01
