_wandb:
    value:
        cli_version: 0.22.3
        e:
            lnf5wnozvusktapyjc8zfvwad2dsddre:
                codePath: Part 1\main.py
                codePathLocal: Part 1\main.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1022387097600"
                        used: "500083032064"
                email: 1670797uab@gmail.com
                executable: C:\Users\ainav\anaconda3\envs\project_paradigms\python.exe
                git:
                    commit: 5948ca883058acd27e104b3ebbc46e28bef4355b
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                host: LAPTOP-3ELO2U09
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong\Part 1\main.py
                python: CPython 3.10.19
                root: C:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong
                startedAt: "2025-11-20T11:39:51.090198Z"
                writerId: lnf5wnozvusktapyjc8zfvwad2dsddre
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.19
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 32
device:
    value: cpu
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
