name: project_paradigms_updated
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - swig
  - cmake
  - ffmpeg
  - wandb
  - jupyter
  - ipykernel
  - pytorch
  - pip:
      # --- Core Libraries ---
      - gymnasium[atari,accept-rom-license]==1.0.0
      - stable-baselines3[extra]
      # CHANGE: We removed [all] and explicitly listed only what is needed for Pong/Atari
      - pettingzoo 
      - shimmy>=2.0.0      # Critical for connecting PettingZoo to Stable Baselines 3
      - supersuit
      - ale-py             # The emulator for Pong and Skiing
      
      # --- Utilities ---
      - moviepy
      - autorom[accept-rom-license]