_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/Part_3/main_aina.py
        e:
            3qfzl0hl8gnjztewvsfgsaxujwe4fcrc:
                args:
                    - --train
                codePath: Part_3\main_aina.py
                codePathLocal: main_aina.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999542947840"
                        used: "896376872960"
                email: ivanmartincampoy@gmail.com
                executable: C:\Users\Iván\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 452554d53bfbc1e5965ed31cd1392206de59cbf8
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-0874ff1a-4d55-a603-929f-30b09fe083f9
                host: Pc-Ivan
                memory:
                    total: "34290769920"
                os: Windows-10-10.0.19045-SP0
                program: C:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong\Part_3\main_aina.py
                python: CPython 3.10.10
                root: C:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong\Part_3
                startedAt: "2025-12-09T20:43:38.975211Z"
                writerId: 3qfzl0hl8gnjztewvsfgsaxujwe4fcrc
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
            "3":
                - 13
                - 16
                - 35
                - 61
            "4": 3.10.10
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 256
clip_range:
    value: 0.1
ent_coef:
    value: 0.03
env_name:
    value: ALE/Skiing-v5
export_path:
    value: ../exports/
gae_lambda:
    value: 0.95
gamma:
    value: 0.999
learning_rate:
    value: 5e-05
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 4
n_steps:
    value: 2048
normalize_advantage:
    value: true
policy_type:
    value: CnnPolicy
total_timesteps:
    value: 10000000
vf_coef:
    value: 1
