_wandb:
    value:
        cli_version: 0.22.3
        e:
            ijgljvlrx9xe8islttt2879byfqc33m9:
                codePath: Part 1\main.py
                codePathLocal: Part 1\main.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1022387097600"
                        used: "498781569024"
                email: 1670797uab@gmail.com
                executable: C:\Users\ainav\anaconda3\envs\project_paradigms\python.exe
                git:
                    commit: 623e7b95b0a666feb1d6dba54dc88202fb115c79
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                host: LAPTOP-3ELO2U09
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong\Part 1\main.py
                python: CPython 3.10.19
                root: C:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong
                startedAt: "2025-11-20T07:35:41.723363Z"
                writerId: ijgljvlrx9xe8islttt2879byfqc33m9
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "4": 3.10.19
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
