_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True  True  True  True  True  True  True  True]'
_last_obs:
    value: |-
        [[[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         [[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         [[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         ...


         [[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         [[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]


         [[[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]

          [[236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           ...
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]
           [236 236 236 ... 236 236 236]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001A0D1CA4AF0>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.23.0
        code_path: code/Part_3/main.py
        e:
            2tvunowhu3gbi6rfkos8pol0qnbhpv8o:
                codePath: Part_3\main.py
                codePathLocal: Part_3\main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999542947840"
                        used: "903071154176"
                email: ivanmartincampoy@gmail.com
                executable: C:\Users\Iván\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 619637efe37aba27ec66c992b9010f319d72b008
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-0874ff1a-4d55-a603-929f-30b09fe083f9
                host: Pc-Ivan
                memory:
                    total: "34290769920"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong\Part_3\main.py
                python: CPython 3.10.10
                root: c:\Users\Iván\Desktop\Project-PML-Pong\Project-PML-Pong
                startedAt: "2025-12-01T10:38:59.550825Z"
                writerId: 2tvunowhu3gbi6rfkos8pol0qnbhpv8o
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
                - 2
                - 3
            "2":
                - 1
                - 2
                - 3
            "3":
                - 2
                - 13
                - 16
                - 22
                - 35
            "4": 3.10.10
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(3)
algo:
    value: PPO
batch_size:
    value: 2048
clip_range:
    value: FloatSchedule(ConstantSchedule(val=0.2))
clip_range_vf:
    value: None
device:
    value: cuda
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001A0F6A0B250>
env_name:
    value: ALE/Skiing-v5
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
export_path:
    value: ./exports/
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.0003
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0003))
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 4096
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: Box(0, 255, (4, 84, 84), uint8)
policy:
    value: |-
        ActorCriticCnnPolicy(
          (features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (pi_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (vf_features_extractor): NatureCNN(
            (cnn): Sequential(
              (0): Conv2d(4, 32, kernel_size=(8, 8), stride=(4, 4))
              (1): ReLU()
              (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))
              (3): ReLU()
              (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))
              (5): ReLU()
              (6): Flatten(start_dim=1, end_dim=-1)
            )
            (linear): Sequential(
              (0): Linear(in_features=3136, out_features=512, bias=True)
              (1): ReLU()
            )
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential()
            (value_net): Sequential()
          )
          (action_net): Linear(in_features=512, out_features=3, bias=True)
          (value_net): Linear(in_features=512, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticCnnPolicy'>
policy_kwargs:
    value: '{}'
policy_type:
    value: CnnPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001A0FE526770>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764585544686791700
target_kl:
    value: None
tensorboard_log:
    value: None
total_timesteps:
    value: 1000000
use_sde:
    value: "False"
verbose:
    value: 1
vf_coef:
    value: 0.5
