_current_progress_remaining:
    value: 1
_custom_logger:
    value: "False"
_episode_num:
    value: 0
_last_episode_starts:
    value: '[ True]'
_last_obs:
    value: |-
        [[[[0.19215687 0.19215687 0.19215687 ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           ...
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]]

          [[0.19215687 0.19215687 0.19215687 ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           ...
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]]

          [[0.19215687 0.19215687 0.19215687 ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           ...
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]]

          [[0.19215687 0.19215687 0.19215687 ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           [0.3254902  0.3254902  0.3254902  ... 0.3254902  0.3254902
            0.3254902 ]
           ...
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]
           [0.9254902  0.9254902  0.9254902  ... 0.9254902  0.9254902
            0.9254902 ]]]]
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x000001E13A315780>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 1000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.22.3
        code_path: code/Part_2/main.py
        e:
            jeilwchq5zfpu7valcmb619id6d01u1h:
                codePath: Part_2\main.py
                codePathLocal: Part_2\main.py
                cpu_count: 16
                cpu_count_logical: 22
                disk:
                    /:
                        total: "1022387097600"
                        used: "549054906368"
                email: 1670797uab@gmail.com
                executable: C:\Users\ainav\anaconda3\envs\project_paradigms\python.exe
                git:
                    commit: 7845af84021d06c11e749d4ca4a12a28e92b15e9
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                host: LAPTOP-3ELO2U09
                memory:
                    total: "16505966592"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong\Part_2\main.py
                python: CPython 3.10.19
                root: C:\Users\ainav\OneDrive\Documents\Uni\4th_year\1st_semester\paradigms_ml\project\Project-PML-Pong
                startedAt: "2025-11-25T16:02:13.609749Z"
                writerId: jeilwchq5zfpu7valcmb619id6d01u1h
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 22
                - 35
            "4": 3.10.19
            "5": 0.22.3
            "8":
                - 3
            "12": 0.22.3
            "13": windows-amd64
action_noise:
    value: None
action_space:
    value: Discrete(6)
algo:
    value: A2C
device:
    value: cpu
ent_coef:
    value: 0
env:
    value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x000001E128D16500>
env_name:
    value: PongNoFrameskip-v4
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
export_path:
    value: ./exports/
gae_lambda:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0007
lr_schedule:
    value: FloatSchedule(ConstantSchedule(val=0.0007))
max_grad_norm:
    value: 0.5
n_envs:
    value: 1
n_steps:
    value: 5
normalize_advantage:
    value: "False"
num_timesteps:
    value: 0
observation_space:
    value: Box(0.0, 1.0, (4, 84, 84), float32)
policy:
    value: |-
        ActorCriticPolicy(
          (features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (pi_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (vf_features_extractor): FlattenExtractor(
            (flatten): Flatten(start_dim=1, end_dim=-1)
          )
          (mlp_extractor): MlpExtractor(
            (policy_net): Sequential(
              (0): Linear(in_features=28224, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
            (value_net): Sequential(
              (0): Linear(in_features=28224, out_features=64, bias=True)
              (1): Tanh()
              (2): Linear(in_features=64, out_features=64, bias=True)
              (3): Tanh()
            )
          )
          (action_net): Linear(in_features=64, out_features=6, bias=True)
          (value_net): Linear(in_features=64, out_features=1, bias=True)
        )
policy_class:
    value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
policy_kwargs:
    value: '{''optimizer_class'': <class ''torch.optim.rmsprop.RMSprop''>, ''optimizer_kwargs'': {''alpha'': 0.99, ''eps'': 1e-05, ''weight_decay'': 0}}'
policy_type:
    value: MlpPolicy
rollout_buffer:
    value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x000001E128DC64A0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
sde_sample_freq:
    value: -1
seed:
    value: None
start_time:
    value: 1764086545416842500
tensorboard_log:
    value: runs/m0yqcq44
total_timesteps:
    value: 1000000
use_sde:
    value: "False"
verbose:
    value: 0
vf_coef:
    value: 0.5
