_wandb:
    value:
        cli_version: 0.22.2
        code_path: code/Part_3/main_aina.py
        e:
            cvd4aafeayxamslvousyy385bg88595z:
                args:
                    - --train
                codePath: Part_3\main_aina.py
                codePathLocal: main_aina.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "511208058880"
                        used: "134238785536"
                email: ivanmartincampoy@gmail.com
                executable: C:\Users\User\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                git:
                    commit: 39890492a7780e3a9287abdcb6172cb45c288fde
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-4984273b-9091-2c63-3433-f397a7312b71
                host: Portatil-Ivan
                memory:
                    total: "25439199232"
                os: Windows-11-10.0.26100-SP0
                program: C:\Users\User\Desktop\Project-PML-Pong\Part_3\main_aina.py
                python: CPython 3.13.9
                root: C:\Users\User\Desktop\Project-PML-Pong\Part_3
                startedAt: "2025-12-09T14:45:41.769643Z"
                writerId: cvd4aafeayxamslvousyy385bg88595z
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
                - 61
            "4": 3.13.9
            "5": 0.22.2
            "8":
                - 3
            "12": 0.22.2
            "13": windows-amd64
batch_size:
    value: 256
clip_range:
    value: 0.1
ent_coef:
    value: 0.03
env_name:
    value: ALE/Skiing-v5
export_path:
    value: ../exports/
gae_lambda:
    value: 0.95
gamma:
    value: 0.999
learning_rate:
    value: 0.0001
max_grad_norm:
    value: 0.5
n_envs:
    value: 8
n_epochs:
    value: 4
n_steps:
    value: 2048
normalize_advantage:
    value: true
policy_type:
    value: CnnPolicy
total_timesteps:
    value: 10000000
vf_coef:
    value: 1
