name: project_paradigms
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - swig
  - pytorch=2.5.1
  - blas
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - expat
  - krb5
  - libffi
  - libsodium
  - libuv
  - openssl
  - sqlite
  - tbb
  - tk
  - xz
  - yaml
  - zeromq
  - intel-openmp
  - mkl
  - mpc
  - mpfr
  - appdirs=1.4.4
  - asttokens=3.0.1
  - brotlicffi=1.1.0.0
  - charset-normalizer=3.4.4
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - docker-pycreds=0.4.0
  - eval_type_backport=0.3.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - filelock=3.20.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - gmp=6.3.0
  - gmpy2=2.2.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - markupsafe=3.0.2
  - matplotlib-inline=0.2.1
  - mpmath=1.3.0
  - nest-asyncio=1.6.0
  - networkx=3.4.2
  - packaging=25.0
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - protobuf=6.33.0
  - psutil=7.1.3
  - pure_eval=0.2.3
  - pycparser=2.23
  - pydantic=1.10.19
  - pygments=2.19.2
  - pysocks=1.7.1
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pytorch-mutex=1.0
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - requests=2.32.5
  - sentry-sdk=2.18.0
  - setproctitle=1.3.6
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - stack_data=0.6.3
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing=3.10.0.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - urllib3=2.5.0
  - wandb=0.22.3
  - wcwidth=0.2.14
  - wheel=0.45.1
  - zipp=3.23.0
  - pip:
    - absl-py==2.3.1
    - ale-py==0.11.2
    - box2d-py==2.3.8
    - cloudpickle==3.1.2
    - contourpy==1.3.2
    - cycler==0.12.1
    - farama-notifications==0.0.4
    - fonttools==4.60.1
    - fsspec==2025.10.0
    - grpcio==1.76.0
    - gymnasium==1.2.2
    - imageio==2.37.2
    - imageio-ffmpeg==0.6.0
    - kiwisolver==1.4.9
    - markdown==3.10
    - markdown-it-py==4.0.0
    - matplotlib==3.10.7
    - mdurl==0.1.2
    - moviepy==2.2.1
    - numpy==2.2.6
    - opencv-python==4.12.0.88
    - pandas==2.3.3
    - pillow==11.3.0
    - proglog==0.1.12
    - pygame==2.6.1
    - pyparsing==3.2.5
    - python-dotenv==1.2.1
    - pytz==2025.2
    - rich==14.2.0
    - seaborn==0.13.2
    - stable-baselines3==2.7.0
    - swig==4.4.0
    - sympy==1.13.1
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tqdm==4.67.1
    - tzdata==2025.2
    - werkzeug==3.1.3