_wandb:
    value:
        cli_version: 0.23.0
        e:
            nt10iv4oeaodvjxj7l8nle82t9rrlb34:
                codePath: Part 1\main.py
                codePathLocal: Part 1\main.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.9"
                disk:
                    /:
                        total: "999542947840"
                        used: "884654825472"
                email: ivanmartincampoy@gmail.com
                executable: C:\Users\Iván\AppData\Local\Programs\Python\Python310\python.exe
                git:
                    commit: 199f12b96a4ab4d81977cb634656c736a35afbc7
                    remote: https://github.com/quejimista/Project-PML-Pong.git
                gpu: NVIDIA GeForce RTX 3070
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 5888
                      memoryTotal: "8589934592"
                      name: NVIDIA GeForce RTX 3070
                      uuid: GPU-0874ff1a-4d55-a603-929f-30b09fe083f9
                host: Pc-Ivan
                memory:
                    total: "34290769920"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\Iván\Desktop\Project-PML-Pong\Part 1\main.py
                python: CPython 3.10.10
                root: C:\Users\Iván\Desktop\Project-PML-Pong
                startedAt: "2025-11-23T14:13:01.299966Z"
                writerId: nt10iv4oeaodvjxj7l8nle82t9rrlb34
        m: []
        python_version: 3.10.10
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
            "4": 3.10.10
            "5": 0.23.0
            "8":
                - 3
            "12": 0.23.0
            "13": windows-amd64
batch_size:
    value: 32
device:
    value: cuda
dnn_sync_freq:
    value: 1000
dnn_update_freq:
    value: 8
epsilon_decay:
    value: 0.995
epsilon_start:
    value: 1
gamma:
    value: 0.99
learning_rate:
    value: 0.0001
min_epsilon:
    value: 0.01
